name: Noir

on:
  push:
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nargo 0.4.0
        run: |
          mkdir -p $HOME/.nargo/bin
          curl -o $HOME/.nargo/bin/nargo-x86_64-unknown-linux-gnu.tar.gz -L https://github.com/noir-lang/noir/releases/download/v0.3.2/nargo-x86_64-unknown-linux-gnu.tar.gz
          tar -xvf $HOME/.nargo/bin/nargo-x86_64-unknown-linux-gnu.tar.gz -C $HOME/.nargo/bin/
          echo -e '\nexport PATH=$PATH:$HOME/.nargo/bin' >> ~/.bashrc
          echo "${HOME}/.nargo/bin" >> $GITHUB_PATH

      - name: Run nargo test
        run: |
          nargo test